import Image from 'next/image'
import Link from 'next/link'

import styles from './styles.module.css'

export function Hero({children}: {children: React.ReactNode}) {
  return (
    <section className={styles.hero}>
      <Link href="/">
        <Image src="/logo-ai.png" alt="StudyBuddy" width={220} height={220} priority />
      </Link>
      <p className="hint">Generated by AI.</p>

      <h1 className={styles.title}>
        Turn the worksheets you have already done into a record of what you
        actually know.
      </h1>

      <p>
        Upload a worksheet, mark what you missed, and StudyBuddy tracks which
        topics are actually costing you marks.
      </p>

      {children}
    </section>
  )
}
